export const FETCH_PHONES_START = 'FETCH_PHONES_START';
export const FETCH_PHONES_SUCCESS = 'FETCH_PHONES_SUCCESS';
export const FETCH_PHONES_ERROR = 'FETCH_PHONES_ERROR';

export const LOAD_MORE_PHONES_START = 'LOAD_MORE_PHONES_START';
export const LOAD_MORE_PHONES_SUCCESS = 'LOAD_MORE_PHONES_SUCCESS';
export const LOAD_MORE_PHONES_ERROR = 'LOAD_MORE_PHONES_ERROR';

export const FETCH_PHONE_BY_ID_START = 'FETCH_PHONE_BY_ID_START';
export const FETCH_PHONE_BY_ID_SUCCESS = 'FETCH_PHONE_BY_ID_SUCCESS';
export const FETCH_PHONE_BY_ID_ERROR = 'FETCH_PHONE_BY_ID_ERROR';

export const ADD_PHONE_TO_BASKET = 'ADD_PHONE_TO_BASKET';

export const SEARCH_PHONE = 'SEARCH_PHONE';

export const FETCH_CATEGORIES_START = 'FETCH_CATEGORIES_START';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
export const FETCH_CATEGORIES_ERROR = 'FETCH_CATEGORIES_ERROR';

export const REMOVE_PHONE_FROM_BASKET = 'REMOVE_PHONE_FROM_BASKET';

export const CLEAN_BASKET = 'CLEAN_BASKET';